### ISSUE TITLE
Consider alternate formats for config files instead of TOML

### ISSUE THREAD

**Issue by sminez** [sminez/ad#110]
[KDL](https://kdl.dev/) can be parsed using the [knuffel crate](https://docs.rs/knuffel/3.2.0/knuffel/index.html) as seen here in [niri](https://github.com/YaLTeR/niri/blob/main/niri-config/src/lib.rs). The structure of KDL (spec found [here](https://kdl.dev/spec/)) is a lot nicer than TOML, particularly for things like the language config which currently uses a TOML array and has bitten several users through the simple issue of writing `[[language]]` instead of `[[languages]]`.

For example, this:
```toml
[[languages]]
name = "bash"
extensions = ["sh", "bash"]
first_lines = ["#!/usr/bin/bash", "#!/usr/bin/sh", "#!/usr/bin/env bash", "#!/usr/bin/env sh"]

[[languages]]
name = "dart"
extensions = ["dart"]
lsp.command = "dart"
lsp.args = ["language-server", "--protocol=lsp"]
lsp.roots = ["melos.yaml", "pubspec.yaml"]

[[languages]]
name = "graphql"
extensions = ["graphql"]

[[languages]]
name = "rust"
extensions = ["rs"]
lsp.command = "rust-analyzer"
lsp.roots = ["Cargo.toml"]
```

(I think) becomes this:
```kdl
languages {
    language "bash" {
        extensions "sh" "bash"
        first_lines "#!/usr/bin/bash" "#!/usr/bin/sh" "#!/usr/bin/env bash" "#!/usr/bin/env sh"
    }
    language "dart" {
        extensions "dart"
        lsp {
            command "dart"
            args "--language-server" "--protocol=lsp"
            roots "melos.yaml" "pubspec.yaml"
        }
    }
    language "graphql" { extensions "graphql" }
    language "rust" {
        extensions "rs"
        lsp {
            command "rust-analyzer"
            roots "Cargo.toml"
        }
    }
}
```

The downside of course being that KDL is a lot less well known.
