### ISSUE TITLE
Remove duplication between "Default" traits and default "Config.toml"

### ISSUE THREAD

**Issue by Romankivs** [sminez/ad#80]
### Problem description

Currently there is information duplication between the ad code (impl of `Default` traits for `Config` struct child structs) and default `Config.toml` (data/config.toml):

For example, `Default` trait implementation for `TsConfig`:
```rust
impl Default for TsConfig {
    fn default() -> Self {
        let home = env::var("HOME").unwrap();

        TsConfig {
            parser_dir: format!("{home}/.ad/tree-sitter/parsers"),
            syntax_query_dir: format!("{home}/.ad/tree-sitter/queries"),
        }
    }
}
```
The same information inside data/config.toml:
```toml
# Configuration for tree-sitter based syntax highlighting. See :help for details on the required
# directory structure.
[tree_sitter]
# The directory to search for compiled *.so files for parsing each language.
parser_dir = "~/.ad/tree-sitter/parsers"
# The directory to search for syntax highlighting queries.
syntax_query_dir = "~/.ad/tree-sitter/queries"
```

This is undesirable as it worsens maintainability and  may result in synchronization issues between the two.

### Proposed solution 

The most elegant solution seems to be to remove defaulted attributes from `Config` struct and instead "merge" default `Config.toml` with the user provided ~/.ad/config.toml during config loading (probably somewhere in `Config::try_load(...)`).
For example if we have:
default config.toml:
```toml
auto_mount = false

name = "rust"
extensions = ["rs"]
lsp.command = "rust-analyzer"
```
user provided config.toml:
```toml
auto_mount = true
expand_tab = true

[[languages]]
lsp.command = "my-analyzer"
lsp.roots = ["Cargo.toml"]
```
resulting config file would look like this:
```toml
auto_mount = true
expand_tab = true

[[languages]]
name = "rust"
extensions = ["rs"]
lsp.command = "my-analyzer"
lsp.roots = ["Cargo.toml"]
```
In other words, two .toml files are combined together with the override priority given to user's .toml config file.

Similar thing is done in helix: https://github.com/helix-editor/helix/blob/master/helix-loader/src/config.rs

As a bonus, this removes the need for user's config file to contain all of the default values for different options.

Let me know what you think about this.

### Is this a feature you have seen in other text editors?

Nvim and helix don't require copied default values to be present in user's config files.
